name: card_io
description: A new flutter plugin project.
version: 0.0.1+1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.card_io
        pluginClass: CardIoPlugin
      ios:
        pluginClass: CardIoPlugin
